theme: jekyll-theme-minimal
title: My Portfolio
description: Welcome to my portfolio! My name is {name}, I am a {grade year} at Rutgers University majoring in {major} with a minor in {minor}. Here you will find projects that I have worked on. 
