theme: jekyll-theme-minimal
title: My Portfolio
description: Welcome to my portfolio! My name is Yise, I am a senior at Rutgers University majoring in Information Technology with a minor in Statistics. Here you will find projects that I have worked on. 
